-- this file was generated by Gennskie

local response = game:HttpGet("https://raw.githubusercontent.com/kezodxyz/KezodX/refs/heads/main/Library.lua")
local result = loadstring(response)()
local response2 = game:HttpGet("https://raw.githubusercontent.com/kezodxyz/KezodX/refs/heads/main/addons/ThemeManager.lua")
local result2 = loadstring(response2)()
local response3 = game:HttpGet("https://raw.githubusercontent.com/kezodxyz/KezodX/refs/heads/main/addons/SaveManager.lua")
local result3 = loadstring(response3)()
local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Lighting = game:GetService("Lighting")
local UserInputService = game:GetService("UserInputService")
local VirtualInputManager = game:GetService("VirtualInputManager")
local Stats = game:GetService("Stats")
local TweenService = game:GetService("TweenService")
Players.LocalPlayer:WaitForChild("PlayerGui")
local Remotes = ReplicatedStorage:WaitForChild("Remotes")
local Attacks = Remotes:WaitForChild("Attacks")
Attacks:WaitForChild("BasicAttack")
local Generator = Remotes:WaitForChild("Generator")
Generator:WaitForChild("SkillCheckResultEvent")
local Items = Remotes:FindFirstChild("Items")
local TwistofFate = Items:FindFirstChild("Twist of Fate")
TwistofFate:FindFirstChild("Fire")
local Flashlight = Items:FindFirstChild("Flashlight")
Flashlight:FindFirstChild("GotBlinded")
RaycastParams.new().FilterType = Enum.RaycastFilterType.Blacklist
Remotes:WaitForChild("EmoteHandler")
local Circle = Drawing.new("Circle")
local Highlight = Instance.new("Highlight")
local Circle2 = Drawing.new("Circle")
Circle.Color = Color3.fromRGB(255, 0, 255)
Circle.Thickness = 1.5
Circle.Filled = false
Circle.Visible = false
Highlight.Name = "VD_VeilTarget"
Highlight.FillColor = Color3.fromRGB(255, 0, 0)
Highlight.OutlineColor = Color3.fromRGB(255, 255, 255)
Highlight.FillTransparency = 0.5
Highlight.OutlineTransparency = 0
Circle2.Thickness = 2
Circle2.Radius = 5
Circle2.Color = Color3.fromRGB(255, 0, 255)
Circle2.Filled = true
Circle2.Visible = false
local CylinderHandleAdornment = Instance.new("CylinderHandleAdornment")
CylinderHandleAdornment.Name = "KYS_ParryRange"
CylinderHandleAdornment.Radius = 8
CylinderHandleAdornment.InnerRadius = 7.85
CylinderHandleAdornment.Height = 0.01
CylinderHandleAdornment.Color3 = Color3.fromRGB(255, 80, 80)
CylinderHandleAdornment.AlwaysOnTop = false
local Terrain = workspace:FindFirstChildOfClass("Terrain")
CylinderHandleAdornment.Adornee = Terrain
CylinderHandleAdornment.Transparency = 1
local CoreGui = game:GetService("CoreGui")
CylinderHandleAdornment.Parent = CoreGui

task.spawn(function(...)
	local Remotes2 = ReplicatedStorage:WaitForChild("Remotes", 5)
	local Items2 = Remotes2:WaitForChild("Items", 5)
	local ParryingDagger = Items2:WaitForChild("Parrying Dagger", 5)
	local parryResult = ParryingDagger:WaitForChild("parryResult", 5)

	parryResult.OnClientEvent:Connect(function(arg)
		task.delay(60, function(...)
		end)
	end)
end)

local players = Players:GetPlayers()

for k, v in pairs(players) do
	v.CharacterAdded:Connect(function(character)
	end)

	local changedSignal = v:GetPropertyChangedSignal("Team")

	changedSignal:Connect(function(arg2)
	end)
end

Players.PlayerAdded:Connect(function(player)
	player.CharacterAdded:Connect(function(character9)
	end)

	local changedSignal2 = player:GetPropertyChangedSignal("Team")

	changedSignal2:Connect(function(arg242)
	end)
end)

task.spawn(function(...)
	task.wait(5)
	local players2 = Players:GetPlayers()

	for k2, v2 in pairs(players2) do
	end

	task.wait(5)
end)

UserInputService.InputBegan:Connect(function(input, gameProcessed)
end)

UserInputService.InputEnded:Connect(function(input2, gameProcessed2)
end)

getgenv().KYS_SetToFSilentAim = function(arg3, arg4)
	local hui = gethui()
	local ToFTargetSelector = hui:FindFirstChild("ToFTargetSelector")
	ToFTargetSelector:Destroy()
	local ScreenGui = Instance.new("ScreenGui")
	ScreenGui.Name = "ToFTargetSelector"
	ScreenGui.ResetOnSpawn = false
	ScreenGui.IgnoreGuiInset = true
	ScreenGui.Parent = hui
	local Frame = Instance.new("Frame")
	Frame.Name = "Main"
	Frame.Size = UDim2.new(0, 180, 0, 126)
	Frame.Position = UDim2.new(0.5, -120, 0, 110)
	Frame.BackgroundColor3 = Color3.fromRGB(16, 18, 24)
	Frame.BorderSizePixel = 0
	Frame.Active = true
	Frame.Parent = ScreenGui
	local UICorner = Instance.new("UICorner", Frame)
	UICorner.CornerRadius = UDim.new(0, 8)
	local UIStroke = Instance.new("UIStroke", Frame)
	UIStroke.Color = Color3.fromRGB(96, 72, 160)
	UIStroke.Thickness = 1
	local Frame2 = Instance.new("Frame")
	Frame2.Size = UDim2.new(1, 0, 0, 28)
	Frame2.BackgroundColor3 = Color3.fromRGB(24, 26, 34)
	Frame2.BorderSizePixel = 0
	Frame2.Parent = Frame
	local UICorner2 = Instance.new("UICorner", Frame2)
	UICorner2.CornerRadius = UDim.new(0, 8)
	local Frame3 = Instance.new("Frame")
	Frame3.Size = UDim2.new(1, 0, 0, 10)
	Frame3.Position = UDim2.new(0, 0, 1, -10)
	Frame3.BackgroundColor3 = Color3.fromRGB(24, 26, 34)
	Frame3.BorderSizePixel = 0
	Frame3.Parent = Frame2
	local Frame4 = Instance.new("Frame")
	Frame4.Size = UDim2.new(1, -34, 1, 0)
	Frame4.BackgroundTransparency = 1
	Frame4.Parent = Frame2
	local TextButton = Instance.new("TextButton")
	TextButton.Size = UDim2.new(0, 28, 1, 0)
	TextButton.Position = UDim2.new(1, -30, 0, 0)
	TextButton.BackgroundTransparency = 1
	TextButton.Text = "-"
	TextButton.TextColor3 = Color3.fromRGB(185, 190, 205)
	TextButton.Font = Enum.Font.GothamBold
	TextButton.TextSize = 14
	TextButton.Parent = Frame2
	local TextLabel = Instance.new("TextLabel")
	TextLabel.Size = UDim2.new(1, -44, 1, 0)
	TextLabel.Position = UDim2.new(0, 10, 0, 0)
	TextLabel.BackgroundTransparency = 1
	TextLabel.Text = "TOF TARGET MODE"
	TextLabel.TextColor3 = Color3.fromRGB(210, 215, 230)
	TextLabel.Font = Enum.Font.GothamBold
	TextLabel.TextSize = 10
	TextLabel.TextXAlignment = Enum.TextXAlignment.Left
	TextLabel.Parent = Frame2
	local Frame5 = Instance.new("Frame")
	Frame5.Size = UDim2.new(1, -16, 0, 86)
	Frame5.Position = UDim2.new(0, 8, 0, 34)
	Frame5.BackgroundTransparency = 1
	Frame5.Parent = Frame
	local UIListLayout = Instance.new("UIListLayout", Frame5)
	UIListLayout.FillDirection = Enum.FillDirection.Vertical
	UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
	UIListLayout.Padding = UDim.new(0, 5)

	TextButton.MouseButton1Click:Connect(function()
		TextButton.Text = "+"
		Frame5.Visible = false
		Frame.Size = UDim2.new(0, 180, 0, 28)
	end)

	local TextButton2 = Instance.new("TextButton")
	TextButton2.Size = UDim2.new(1, 0, 0, 25)
	TextButton2.BorderSizePixel = 0
	TextButton2.Font = Enum.Font.GothamBold
	TextButton2.TextSize = 11
	TextButton2.Text = "KILLER        K"
	TextButton2.TextXAlignment = Enum.TextXAlignment.Center
	TextButton2.LayoutOrder = 1
	TextButton2.Parent = Frame5
	local UICorner3 = Instance.new("UICorner", TextButton2)
	UICorner3.CornerRadius = UDim.new(0, 6)
	local UIStroke2 = Instance.new("UIStroke", TextButton2)
	UIStroke2.Color = Color3.fromRGB(58, 62, 78)
	UIStroke2.Thickness = 1

	TextButton2.MouseButton1Click:Connect(function()
		result:Notify({ Title = "ToF Target", Description = "Killer", Time = 2 })
	end)

	TextButton2.InputEnded:Connect(function(input3, gameProcessed3)
	end)

	local TextButton3 = Instance.new("TextButton")
	TextButton3.Size = UDim2.new(1, 0, 0, 25)
	TextButton3.BorderSizePixel = 0
	TextButton3.Font = Enum.Font.GothamBold
	TextButton3.TextSize = 11
	TextButton3.Text = "SURVIVOR      J"
	TextButton3.TextXAlignment = Enum.TextXAlignment.Center
	TextButton3.LayoutOrder = 2
	TextButton3.Parent = Frame5
	local UICorner4 = Instance.new("UICorner", TextButton3)
	UICorner4.CornerRadius = UDim.new(0, 6)
	local UIStroke3 = Instance.new("UIStroke", TextButton3)
	UIStroke3.Color = Color3.fromRGB(58, 62, 78)
	UIStroke3.Thickness = 1

	TextButton3.MouseButton1Click:Connect(function()
		result:Notify({ Title = "ToF Target", Description = "Survivors", Time = 2 })
	end)

	TextButton3.InputEnded:Connect(function(input4, gameProcessed4)
	end)

	local TextButton4 = Instance.new("TextButton")
	TextButton4.Size = UDim2.new(1, 0, 0, 25)
	TextButton4.BorderSizePixel = 0
	TextButton4.Font = Enum.Font.GothamBold
	TextButton4.TextSize = 11
	TextButton4.Text = "ZOMBIE        L"
	TextButton4.TextXAlignment = Enum.TextXAlignment.Center
	TextButton4.LayoutOrder = 3
	TextButton4.Parent = Frame5
	local UICorner5 = Instance.new("UICorner", TextButton4)
	UICorner5.CornerRadius = UDim.new(0, 6)
	local UIStroke4 = Instance.new("UIStroke", TextButton4)
	UIStroke4.Color = Color3.fromRGB(58, 62, 78)
	UIStroke4.Thickness = 1

	TextButton4.MouseButton1Click:Connect(function()
		result:Notify({ Title = "ToF Target", Description = "Zombie", Time = 2 })
	end)

	TextButton4.InputEnded:Connect(function(input5, gameProcessed5)
	end)

	TextButton3.BackgroundColor3 = Color3.fromRGB(30, 32, 40)
	TextButton3.TextColor3 = Color3.fromRGB(155, 160, 175)
	TextButton2.BackgroundColor3 = Color3.fromRGB(180, 45, 45)
	TextButton2.TextColor3 = Color3.fromRGB(255, 180, 180)
	TextButton4.BackgroundColor3 = Color3.fromRGB(30, 32, 40)
	TextButton4.TextColor3 = Color3.fromRGB(155, 160, 175)

	Frame4.InputBegan:Connect(function(input6, gameProcessed6)
	end)

	Frame4.InputEnded:Connect(function(input7, gameProcessed7)
	end)

	UserInputService.InputChanged:Connect(function(input8, gameProcessed8)
	end)

	local connection = RunService.Heartbeat:Connect(function(deltaTime)
	end)
end

getgenv().KYS_ToFClearLaser = function(arg5, arg6)
end

getgenv().KYS_ToFSetTargetMode = function(arg7, arg8)
end

result.ForceCheckbox = false
result.ShowToggleFrameInKeybinds = true
result.Scheme.AccentColor = Color3.fromRGB(0, 255, 255)
result.Scheme.BackgroundColor = Color3.fromRGB(8, 12, 20)
result.Scheme.MainColor = Color3.fromRGB(14, 20, 35)
result.Scheme.OutlineColor = Color3.fromRGB(0, 180, 255)
result.Scheme.FontColor = Color3.fromRGB(180, 240, 255)

local Window = result:CreateWindow({
	Title = "Kanzyu_Script",
	AutoShow = true,
	CornerRadius = 20,
	EnableCompacting = true,
	EnableSidebarResize = true,
	Footer = "TT kanzyu_script | YT kanzyu_script",
	Icon = "136681914611819",
	IconSize = UDim2.fromOffset(50, 50),
	NotifySide = "Right",
	SidebarCompacted = true,
	Size = UDim2.fromOffset(450, 1000)
})

local Tab = Window:AddTab("Info", "info", "Information, Credit")
local Tab2 = Window:AddTab("ESP", "eye", "Esp player, object, stats")
local Tab3 = Window:AddTab("Player", "user", "Ability Survivor & Killer")
local Tab4 = Window:AddTab("Misc", "sliders-horizontal", "Movement, Emote, Fun")
local Tab5 = Window:AddTab("Visual", "sparkles", "Graphics, MorphAva, Time")
local Tab6 = Window:AddTab("UI Settings", "settings-2", "Config, Theme, UiSetting")
local LeftGroupbox = Tab:AddLeftGroupbox("Script Info", "info")
local RightGroupbox = Tab:AddRightGroupbox("Credits", "user")
local LeftGroupbox2 = Tab2:AddLeftGroupbox("ESP Cham", "scan-eye")
local RightGroupbox2 = Tab2:AddRightGroupbox("ESP Status", "scan-eye")
local RightTabbox = Tab3:AddRightTabbox()
local Tab7 = RightTabbox:AddTab("Survivor", "user")
local Tab8 = RightTabbox:AddTab("Killer", "skull")
local LeftGroupbox3 = Tab3:AddLeftGroupbox("AimBot", "crosshair")
local LeftGroupbox4 = Tab3:AddLeftGroupbox("Twist of Fate", "target")
local LeftGroupbox5 = Tab3:AddLeftGroupbox("Parry", "swords")
local LeftGroupbox6 = Tab3:AddLeftGroupbox("Crosshair", "crosshair")
local LeftGroupbox7 = Tab4:AddLeftGroupbox("Movement", "move")
local RightGroupbox3 = Tab4:AddRightGroupbox("Fake Chat Tag", "message-circle")
local LeftGroupbox8 = Tab5:AddLeftGroupbox("Graphics", "sun")
local LeftGroupbox9 = Tab5:AddLeftGroupbox("Morph Avatar", "user")
local RightGroupbox4 = Tab5:AddRightGroupbox("Clock & Ambient", "alarm-clock-check")
local RightGroupbox5 = Tab5:AddRightGroupbox("Zoom Out", "fullscreen")
local LeftGroupbox10 = Tab6:AddLeftGroupbox("Menu", "wrench")
local Remotes3 = ReplicatedStorage:FindFirstChild("Remotes")
local Mechanics = Remotes3:FindFirstChild("Mechanics")
Mechanics:FindFirstChild("Fall")
local descendants = workspace:GetDescendants()

for i, v4 in ipairs(descendants) do
end

workspace.DescendantAdded:Connect(function(descendant)
end)

workspace.DescendantRemoving:Connect(function(descendant2)
end)

hookmetamethod(game, "__namecall", function(arg9, arg10)
end)

UserInputService.InputBegan:Connect(function(input9, gameProcessed9)
end)

UserInputService.InputEnded:Connect(function(input10, gameProcessed10)
end)

UserInputService.InputBegan:Connect(function(input11, gameProcessed11)
end)

UserInputService.InputEnded:Connect(function(input12, gameProcessed12)
end)

RunService.RenderStepped:Connect(function(deltaTime2)
	Players.LocalPlayer.Character:GetAttribute("spearmode")
	Circle.Visible = false
	Highlight.Parent = nil
	Circle2.Visible = false
end)

task.spawn(function(...)
	task.wait(0.2)
	task.wait(0.2)
end)

local TextChatService = game:GetService("TextChatService")

TextChatService.OnIncomingMessage = function(arg11, arg12)
	Instance.new("TextChatMessageProperties")
end

Lighting.ChildAdded:Connect(function(child)
end)

local BypassGenUI = Players.LocalPlayer.PlayerGui:FindFirstChild("BypassGenUI")
BypassGenUI:Destroy()
local ScreenGui2 = Instance.new("ScreenGui")
ScreenGui2.Name = "BypassGenUI"
ScreenGui2.ResetOnSpawn = false
ScreenGui2.IgnoreGuiInset = true
local PlayerGui = Players.LocalPlayer:WaitForChild("PlayerGui")
ScreenGui2.Parent = PlayerGui
local ImageButton = Instance.new("ImageButton")
ImageButton.Name = "BypassGenButton"
ImageButton.Size = UDim2.new(0, 60, 0, 60)
ImageButton.Position = UDim2.new(0.88, 0, 0.55, 0)
ImageButton.AnchorPoint = Vector2.new(0.5, 0.5)
ImageButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
ImageButton.BackgroundTransparency = 0.15
ImageButton.AutoButtonColor = true
ImageButton.Visible = false
ImageButton.ZIndex = 10
ImageButton.Parent = ScreenGui2
local UICorner6 = Instance.new("UICorner", ImageButton)
UICorner6.CornerRadius = UDim.new(1, 0)
local UIStroke5 = Instance.new("UIStroke", ImageButton)
UIStroke5.Color = Color3.fromRGB(0, 255, 255)
UIStroke5.Thickness = 2
UIStroke5.Transparency = 0.2
local TextLabel2 = Instance.new("TextLabel", ImageButton)
TextLabel2.Size = UDim2.new(1, 0, 1, 0)
TextLabel2.BackgroundTransparency = 1
TextLabel2.Text = "K"
TextLabel2.TextColor3 = Color3.fromRGB(255, 255, 255)
TextLabel2.TextScaled = true
TextLabel2.Font = Enum.Font.GothamBlack
TextLabel2.ZIndex = 11

ImageButton.MouseButton1Click:Connect(function()
end)

Players.LocalPlayer.CharacterAdded:Connect(function(character2)
	task.wait(0.5)
	local BypassGenUI2 = Players.LocalPlayer.PlayerGui:FindFirstChild("BypassGenUI")
	BypassGenUI2:Destroy()
	local ScreenGui3 = Instance.new("ScreenGui")
	ScreenGui3.Name = "BypassGenUI"
	ScreenGui3.ResetOnSpawn = false
	ScreenGui3.IgnoreGuiInset = true
	local PlayerGui4 = Players.LocalPlayer:WaitForChild("PlayerGui")
	ScreenGui3.Parent = PlayerGui4
	local ImageButton2 = Instance.new("ImageButton")
	ImageButton2.Name = "BypassGenButton"
	ImageButton2.Size = UDim2.new(0, 60, 0, 60)
	ImageButton2.Position = UDim2.new(0.88, 0, 0.55, 0)
	ImageButton2.AnchorPoint = Vector2.new(0.5, 0.5)
	ImageButton2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
	ImageButton2.BackgroundTransparency = 0.15
	ImageButton2.AutoButtonColor = true
	ImageButton2.Visible = false
	ImageButton2.ZIndex = 10
	ImageButton2.Parent = ScreenGui3
	local UICorner7 = Instance.new("UICorner", ImageButton2)
	UICorner7.CornerRadius = UDim.new(1, 0)
	local UIStroke6 = Instance.new("UIStroke", ImageButton2)
	UIStroke6.Color = Color3.fromRGB(0, 255, 255)
	UIStroke6.Thickness = 2
	UIStroke6.Transparency = 0.2
	local TextLabel3 = Instance.new("TextLabel", ImageButton2)
	TextLabel3.Size = UDim2.new(1, 0, 1, 0)
	TextLabel3.BackgroundTransparency = 1
	TextLabel3.Text = "K"
	TextLabel3.TextColor3 = Color3.fromRGB(255, 255, 255)
	TextLabel3.TextScaled = true
	TextLabel3.Font = Enum.Font.GothamBlack
	TextLabel3.ZIndex = 11

	ImageButton2.MouseButton1Click:Connect(function()
	end)

	ImageButton2.Visible = false
end)

UserInputService.InputBegan:Connect(function(input13, gameProcessed13)
end)

UserInputService.InputBegan:Connect(function(input14, gameProcessed14)
end)

task.spawn(function(...)
	task.wait(2)
	Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
	task.wait(2)
	Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
	task.wait(2)
end)

Players.LocalPlayer.CharacterAdded:Connect(function(character3)
	task.wait(0.8)
	connection3:Disconnect()

	RunService.Heartbeat:Connect(function(deltaTime12)
	end)
end)

Players.LocalPlayer.CharacterAdded:Connect(function(character4)
	task.wait(0.8)
end)

Players.LocalPlayer.CharacterAdded:Connect(function(character5)
	task.wait(1)
	workspace.CurrentCamera.FieldOfView = 70
end)

Players.LocalPlayer.CharacterAdded:Connect(function(character6)
	task.wait(0.5)
	Players.LocalPlayer.CameraMaxZoomDistance = 128
	Players.LocalPlayer.CameraMinZoomDistance = 0.5
	local Humanoid5 = character6:FindFirstChildOfClass("Humanoid")
	local Animator2 = Humanoid5:FindFirstChildOfClass("Animator")

	Animator2.AnimationPlayed:Connect(function(arg243)
	end)
end)

RunService.Heartbeat:Connect(function(deltaTime3)
end)

RunService.RenderStepped:Connect(function(deltaTime4)
	Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
	local players3 = Players:GetPlayers()

	for k7, v12 in pairs(players3) do
		v12.Character:FindFirstChildOfClass("Humanoid")
	end
end)

RunService.RenderStepped:Connect(function(deltaTime5)
end)

local Humanoid = Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
local Animator = Humanoid:FindFirstChildOfClass("Animator")

Animator.AnimationPlayed:Connect(function(arg13)
end)

RunService.RenderStepped:Connect(function(deltaTime6)
end)

LeftGroupbox:AddLabel("Script: kanzyu")
LeftGroupbox:AddLabel("Version: 1.1.1")
LeftGroupbox:AddLabel("Game: Violence District")

LeftGroupbox:AddButton("Copy Saluran Link", function(arg14, arg15)
	setclipboard("https://whatsapp.com/channel/0029VbCz0u94IBh9AIJTiJ1R")
	result:Notify({ Title = "Saluran link copied!", Duration = 3 })
end)

LeftGroupbox:AddLabel("Join discord for more info")
LeftGroupbox:AddLabel("Discord:")

LeftGroupbox:AddButton("Copy Discord Link", function(arg16, arg17)
	setclipboard("https://discord.gg/ec6DGUgNC")
	result:Notify({ Title = "Discord link copied!", Duration = 3 })
end)

RightGroupbox:AddLabel("Developer:")
RightGroupbox:AddLabel("â€¢ Kanzyu_script")
RightGroupbox:AddDivider()
RightGroupbox:AddLabel("Library:")
RightGroupbox:AddLabel("â€¢ Obsidian UI")
RightGroupbox:AddDivider()
RightGroupbox:AddLabel("Support the dev:")

RightGroupbox:AddButton("Copy Support Link", function(arg18, arg19)
	setclipboard("https://saweria.co/kanzyuscrpt")
	result:Notify({ Title = "Thanks for the support!", Duration = 3 })
end)

local Checkbox = LeftGroupbox2:AddCheckbox("SurvivorESP", {
	Text = "ESP Survivor",
	Default = false,
	Callback = function(state, arg21)
	end
})

Checkbox:AddColorPicker("SurvivorESPColor", {
	Title = "Survivor Color",
	Default = Color3.fromRGB(0, 0, 139),
	Callback = function(state, arg23)
	end
})

local Checkbox2 = LeftGroupbox2:AddCheckbox("KillerESP", {
	Text = "ESP Killer",
	Default = false,
	Callback = function(state, arg25)
	end
})

Checkbox2:AddColorPicker("KillerESPColor", {
	Title = "Killer Color",
	Default = Color3.fromRGB(255, 60, 60),
	Callback = function(state, arg27)
	end
})

local Checkbox3 = LeftGroupbox2:AddCheckbox("ESPGenerator", {
	Text = "Generator",
	Default = false,
	Callback = function(state, arg29)
	end
})

Checkbox3:AddColorPicker("GeneratorColor", {
	Title = "Generator Color",
	Default = Color3.fromRGB(255, 170, 0),
	Callback = function(state, arg31)
	end
})

local Checkbox4 = LeftGroupbox2:AddCheckbox("ESPHook", {
	Text = "Hook",
	Default = false,
	Callback = function(state, arg33)
	end
})

Checkbox4:AddColorPicker("HookColor", {
	Title = "Hook Color",
	Default = Color3.fromRGB(204, 204, 0),
	Callback = function(state, arg35)
	end
})

local Checkbox5 = LeftGroupbox2:AddCheckbox("ESPSCP", {
	Text = "SCP",
	Default = false,
	Callback = function(state, arg37)
	end
})

Checkbox5:AddColorPicker("SCPColor", {
	Title = "SCP Color",
	Default = Color3.fromRGB(255, 255, 102),
	Callback = function(state, arg39)
	end
})

local Checkbox6 = LeftGroupbox2:AddCheckbox("ESPPallet", {
	Text = "Pallet",
	Default = false,
	Callback = function(state, arg41)
	end
})

Checkbox6:AddColorPicker("PalletColor", {
	Title = "Pallet Color",
	Default = Color3.fromRGB(144, 238, 144),
	Callback = function(state, arg43)
	end
})

local Checkbox7 = LeftGroupbox2:AddCheckbox("ESPWindow", {
	Text = "Window",
	Default = false,
	Callback = function(state, arg45)
	end
})

Checkbox7:AddColorPicker("WindowColor", {
	Title = "Window Color",
	Default = Color3.fromRGB(74, 255, 181),
	Callback = function(state, arg47)
	end
})

LeftGroupbox2:AddSlider("ESPDistance", {
	Text = "ESP Radius",
	Default = 100,
	Max = 1000,
	Min = 10,
	Rounding = 0,
	Callback = function(state, arg49)
	end
})

RightGroupbox2:AddCheckbox("EnableStatus", {
	Text = "Enable Status ESP",
	Default = false,
	Callback = function(state, arg51)
	end
})

RightGroupbox2:AddCheckbox("ShowName", {
	Text = "Show Name",
	Default = true,
	Callback = function(state, arg53)
	end
})

RightGroupbox2:AddCheckbox("ShowItemESP", {
	Text = "Show Item",
	Default = true,
	Callback = function(state, arg55)
	end
})

RightGroupbox2:AddCheckbox("ShowDistance", {
	Text = "Show Distance",
	Default = true,
	Callback = function(state, arg57)
	end
})

RightGroupbox2:AddCheckbox("ShowHealth", {
	Text = "Show Health",
	Default = false,
	Callback = function(state, arg59)
	end
})

RightGroupbox2:AddSlider("StatusRadius", {
	Text = "Status Radius",
	Default = 100,
	Max = 500,
	Min = 20,
	Rounding = 0,
	Callback = function(state, arg61)
	end
})

local Checkbox8 = LeftGroupbox6:AddCheckbox("CrosshairEnabled", {
	Text = "Enable Crosshair",
	Default = false,
	Callback = function(state, arg63)
	end
})

Checkbox8:AddColorPicker("CrosshairColor", {
	Title = "Crosshair Color",
	Default = Color3.fromRGB(255, 255, 255),
	Transparency = 0,
	Callback = function(state, arg65)
	end
})

LeftGroupbox6:AddDropdown("Style", {
	Text = "Style",
	Default = 1,
	Multi = false,
	Values = { "Plus", "Dot", "Circle" },
	Callback = function(state, arg67)
	end
})

LeftGroupbox6:AddSlider("CrosshairPosX", {
	Text = "Position X",
	Default = 0,
	Max = 100,
	Min = -100,
	Rounding = 0,
	Callback = function(state, arg69)
	end
})

LeftGroupbox6:AddSlider("CrosshairPosY", {
	Text = "Position Y",
	Default = 0,
	Max = 100,
	Min = -100,
	Rounding = 0,
	Callback = function(state, arg71)
	end
})

Tab7:AddCheckbox("Skill", {
	Text = "Auto Skill Check",
	Default = false,
	Callback = function(state, arg73)
		if state then
			RunService.RenderStepped:Connect(function(deltaTime7)
			end)
		end
	end
})

Tab7:AddDropdown("SkillCheckModeDropdown", {
	Text = "Skill Check Mode",
	Default = 1,
	Multi = false,
	Values = { "Legit", "Instant" },
	Callback = function(state, arg75)
	end
})

Tab7:AddCheckbox("GenBypassToggle", {
	Text = "Genboost",
	Default = false,
	Tooltip = "Otomatis repair semua titik generator di dekatmu.",
	Callback = function(state, arg77)
		if state then
			ImageButton.Visible = UserInputService.TouchEnabled
		else
			ImageButton.Visible = false
		end
	end
})

Tab7:AddCheckbox("AutoPalletDrop", {
	Text = "Auto Drop Pallet",
	Default = false,
	Tooltip = "otomatis menjatuhkan pallet",
	Callback = function(state, arg79)
	end
})

Tab7:AddSlider("AutoPalletDist", {
	Text = "Auto Pallet Distance",
	Default = 6,
	Max = 50,
	Min = 5,
	Rounding = 0,
	Callback = function(state, arg81)
	end
})

Tab7:AddCheckbox("AutoFleeKiller", {
	Text = "Auto Flee Killer",
	Default = false,
	Tooltip = "otomatis tp menjauh dari killer",
	Callback = function(state, arg83)
	end
})

Tab7:AddCheckbox("AntiFallDamage", {
	Text = "Anti Fall Damage",
	Default = false,
	Tooltip = "memblokir efek slow ketika jatuh",
	Callback = function(state, arg85)
	end
})

Tab7:AddCheckbox("GodMode", {
	Text = "Anti KnockDown",
	Default = false,
	Tooltip = "memaksa berdiri ketika KnockDown",
	Callback = function(state, arg87)
	end
})

Tab7:AddCheckbox("FastVault", {
	Text = "Fast Vault",
	Default = false,
	Tooltip = "percepat animasi lompat",
	Callback = function(state, arg89)
	end
})

Tab7:AddSlider("VaultSpeed", {
	Text = "Animation Speed",
	Default = 1.2,
	Max = 5,
	Min = 1,
	Rounding = 1,
	Callback = function(state, arg91)
	end
})

Tab7:AddCheckbox("AntiVault", {
	Text = "Disable Local Vault",
	Default = false,
	Tooltip = "Mencegah karaktermu melakukan vault (berguna agar tidak salah tekan saat dikejar)",
	Callback = function(state, arg93)
	end
})

Tab7:AddDivider()

Tab7:AddButton({
	Text = "instan escape",
	Func = function(arg94, arg95)
		Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
		local descendants2 = workspace:GetDescendants()

		for i2, v5 in ipairs(descendants2) do
		end

		warn("fininshline not found")
	end
})

Tab8:AddLabel("Veil Spear Assist")

Tab8:AddToggle("VeilEnabled", {
	Text = "Enable Veil Assist",
	Default = false,
	Callback = function(state, arg97)
	end
})

Tab8:AddToggle("VeilShowFOV", {
	Text = "Show FOV Circle",
	Default = true,
	Callback = function(state, arg99)
	end
})

Tab8:AddToggle("VeilShowLaser", {
	Text = "Show Target Laser",
	Default = true,
	Callback = function(state, arg101)
	end
})

Tab8:AddToggle("VeilAutoPredict", {
	Text = "Auto Predict",
	Default = false,
	Callback = function(state, arg103)
	end
})

Tab8:AddToggle("VeilInfLakeMist", {
	Text = "Infinite LakeMist",
	Default = false,
	Callback = function(state, arg105)
	end
})

Tab8:AddToggle("VeilInfPursuit", {
	Text = "Infinite Pursuit",
	Default = false,
	Callback = function(state, arg107)
	end
})

Tab8:AddSlider("VeilFOV", {
	Text = "FOV",
	Default = 150,
	Max = 500,
	Min = 10,
	Rounding = 0,
	Callback = function(state, arg109)
	end
})

Tab8:AddSlider("VeilSpearSpeed", {
	Text = "Spear Speed",
	Default = 165,
	Max = 300,
	Min = 20,
	Rounding = 0,
	Callback = function(state, arg111)
	end
})

Tab8:AddSlider("VeilGravity", {
	Text = "Gravity",
	Default = 5,
	Max = 200,
	Min = 0,
	Rounding = 1,
	Callback = function(state, arg113)
	end
})

Tab8:AddSlider("VeilMaxDist", {
	Text = "Max Distance",
	Default = 200,
	Max = 500,
	Min = 10,
	Rounding = 0,
	Callback = function(state, arg115)
	end
})

Tab8:AddSlider("VeilPredictFactor", {
	Text = "Prediction Factor",
	Default = 1,
	Max = 3,
	Min = 0,
	Rounding = 2,
	Callback = function(state, arg117)
	end
})

Tab8:AddDropdown("VeilTargetPart", {
	Text = "Target Part",
	Default = 1,
	Multi = false,
	Values = { "Torso", "Head", "Root" },
	Callback = function(state, arg119)
	end
})

Tab8:AddDivider()

Tab8:AddCheckbox("BlockAllVaults", {
	Text = "Block All Vaults",
	Default = false,
	Tooltip = "memicu Entity Blocker (Mencegah Survivor Vault)",
	Callback = function(state, arg121)
	end
})

Tab8:AddCheckbox("AntiBlindToggle", {
	Text = "Anti Blind (Flashlight)",
	Default = false,
	Callback = function(state, arg123)
	end
})

Tab8:AddCheckbox("AutoStalk", {
	Text = "Auto Stalk (myers)",
	Default = false,
	Callback = function(state, arg125)
		if state then
			local connection2 = RunService.Heartbeat:Connect(function(deltaTime8)
			end)
		else
			connection2:Disconnect()
		end
	end
})

Tab8:AddCheckbox("BypassCooldown", {
	Text = "Bypass Cooldown(Abyss)",
	Default = false,
	Callback = function(state, arg127)
		if state then
			warn("Fungsi corruptHandler tidak ditemukan di memori.")
			result:Notify({ Title = "Bypass Cooldown", Description = "Diaktifkan", Duration = 3 })
		else
			result:Notify({ Title = "Bypass Cooldown", Description = "Dinonaktifkan", Duration = 3 })
		end
	end
})

Tab8:AddCheckbox("BypassLeapCooldown", {
	Text = "Bypass Cooldown(Hidden)",
	Default = false,
	Callback = function(state, arg129)
		if state then
			task.spawn(function(...)
				warn("Function tidak ditemukan.")
			end)
		end
	end
})

Tab8:AddCheckbox("KillAll", {
	Text = "Auto Kill All",
	Default = false,
	Callback = function(state, arg131)
	end
})

Tab8:AddCheckbox("AttackAim", {
	Text = "AimLock Attack",
	Default = false,
	Callback = function(state, arg133)
		if state then
			RunService.RenderStepped:Connect(function(deltaTime9)
			end)
		end
	end
})

Tab8:AddDropdown("AttackAimMode", {
	Text = "Aimlock Mode",
	Default = 1,
	Multi = false,
	Values = { "Normal", "Spear" },
	Callback = function(state, arg135)
	end
})

Tab8:AddSlider("SpearGravity", {
	Text = "Spear Gravity",
	Default = 50,
	Max = 200,
	Min = 10,
	Rounding = 0,
	Callback = function(state, arg137)
	end
})

Tab8:AddSlider("SpearSpeed", {
	Text = "Spear Speed",
	Default = 100,
	Max = 300,
	Min = 20,
	Rounding = 0,
	Callback = function(state, arg139)
	end
})

Tab8:AddDivider()

Tab8:AddDropdown("MaskedPowerSelect", {
	Text = "Select Power",
	Default = 1,
	Multi = false,
	Values = { "Cobra", "Richter", "Brandon", "Rabbit", "Alex" },
	Callback = function(state, arg141)
	end
})

Tab8:AddButton("Activate Power", function(arg142, arg143)
	ReplicatedStorage:FindFirstChild("Remotes", true)
	ReplicatedStorage.Remotes:FindFirstChild("Killers", true)
	ReplicatedStorage.Remotes.Killers:FindFirstChild("Masked", true)
	local Activatepower = ReplicatedStorage.Remotes.Killers.Masked:FindFirstChild("Activatepower")
	Activatepower:FireServer(false)
end)

Tab8:AddButton("Deactivate Power", function(arg144, arg145)
	ReplicatedStorage:FindFirstChild("Remotes", true)
	ReplicatedStorage.Remotes:FindFirstChild("Killers", true)
	ReplicatedStorage.Remotes.Killers:FindFirstChild("Masked", true)
	local Deactivatepower = ReplicatedStorage.Remotes.Killers.Masked:FindFirstChild("Deactivatepower")
	Deactivatepower:FireServer()
end)

local Checkbox9 = LeftGroupbox5:AddCheckbox("AutoParry", {
	Text = "Auto Parry",
	Default = false,
	Callback = function(state, arg147)
		CylinderHandleAdornment.Transparency = 1

		if state then
			CylinderHandleAdornment.Transparency = 1
		end
	end
})

Checkbox9:AddColorPicker("ParryRangeColor", {
	Title = "Parry Range Color",
	Default = Color3.fromRGB(255, 80, 80),
	Transparency = 0,
	Callback = function(state, arg149)
		if state then
			CylinderHandleAdornment.Color3 = state
		else
			CylinderHandleAdornment.Color3 = false
		end
	end
})

LeftGroupbox5:AddCheckbox("ShowParryRange", {
	Text = "Show Parry Range",
	Default = true,
	Callback = function(state, arg151)
		if not state then
			CylinderHandleAdornment.Transparency = 1
		end
	end
})

LeftGroupbox5:AddSlider("ParryDistance", {
	Text = "Distance",
	Default = 8,
	Max = 20,
	Min = 5,
	Rounding = 0,
	Callback = function(state, arg153)
	end
})

LeftGroupbox5:AddCheckbox("AggressiveMode", {
	Text = "Aggressive Mode",
	Default = false,
	Tooltip = "Parry lebih agresif: menunggu mendekat jika dalam jarak deteksi",
	Callback = function(state, arg155)
	end
})

LeftGroupbox5:AddSlider("FaceSensitivity", {
	Text = "Face Sensitivity Killer",
	Default = 0.3,
	Max = 1,
	Min = -1,
	Rounding = 2,
	Callback = function(state, arg157)
	end
})

LeftGroupbox3:AddToggle("GunAimEnabled", {
	Text = "Aim Lock",
	Default = false,
	Callback = function(state, arg159)
	end
})

LeftGroupbox3:AddDropdown("GunAimTarget", {
	Text = "Target",
	Default = 1,
	Values = { "Killer", "Survivor", "SCP" },
	Callback = function(state, arg161)
	end
})

LeftGroupbox3:AddDropdown("GunAimPart", {
	Text = "Aim Part",
	Default = 2,
	Values = { "Head", "HumanoidRootPart", "Torso" },
	Callback = function(state, arg163)
	end
})

LeftGroupbox3:AddSlider("GunAimFOV", {
	Text = "FOV",
	Default = 250,
	Max = 1000,
	Min = 50,
	Rounding = 0,
	Callback = function(state, arg165)
	end
})

LeftGroupbox3:AddSlider("GunAimPredict", {
	Text = "Prediction",
	Default = 0.12,
	Max = 1,
	Min = 0,
	Rounding = 2,
	Callback = function(state, arg167)
	end
})

LeftGroupbox4:AddToggle("ToFAimToggle", {
	Text = "Silent Aim Twist of Fate",
	Default = false,
	Callback = function(state, arg169)
		if state then
			gethui()
		else
			ScreenGui:Destroy()
			connection:Disconnect()
		end
	end
})

LeftGroupbox4:AddDropdown("ToFAimTarget", {
	Text = "Target Mode",
	Default = 1,
	Values = { "Killer", "Survivors", "Zombie" },
	Callback = function(state, arg171)
	end
})

LeftGroupbox4:AddToggle("ToFAimPredict", {
	Text = "Aim Prediction",
	Default = true,
	Callback = function(state, arg173)
	end
})

LeftGroupbox4:AddToggle("ToFAimLaser", {
	Text = "Show Laser",
	Default = true,
	Callback = function(state, arg175)
	end
})

LeftGroupbox4:AddToggle("ToFAimWallCheck", {
	Text = "Wall Check",
	Default = false,
	Callback = function(state, arg177)
	end
})

LeftGroupbox4:AddToggle("ToFAimBlockKnocked", {
	Text = "Block When Knocked",
	Default = true,
	Callback = function(state, arg179)
	end
})

LeftGroupbox4:AddSlider("ToFPredictSpeed", {
	Text = "Predict Bullet Speed",
	Default = 400,
	Max = 1500,
	Min = 100,
	Rounding = 0,
	Callback = function(state, arg181)
	end
})

LeftGroupbox4:AddSlider("ToFVerticalDot", {
	Text = "Vertical Dot (Survivor/Zombie)",
	Default = 0.5,
	Max = 1,
	Min = -1,
	Rounding = 2,
	Callback = function(state, arg183)
	end
})

LeftGroupbox4:AddDropdown("ToFKeybind", {
	Text = "Toggle Key",
	Default = 1,
	Values = { "None", "Q", "E", "R", "T", "F", "G", "H", "J", "K", "L", "X", "Z" },
	Callback = function(state, arg185)
	end
})

LeftGroupbox7:AddCheckbox("WalkSpeedToggle", {
	Text = "Walk Speed",
	Default = false,
	Callback = function(state, arg187)
		if state then
			local connection3 = RunService.Heartbeat:Connect(function(deltaTime10)
			end)
		else
			local Humanoid2 = Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
			Humanoid2.WalkSpeed = 16
		end
	end
})

LeftGroupbox7:AddButton({
	Text = "Fly GUI",
	Func = function(arg188, arg189)
		local children = game.CoreGui:GetChildren()

		for k4, v6 in pairs(children) do
			local result4 = v6.Name:lower()
			result4:find("fly")
		end

		result:Notify({ Title = "Fly", Description = "Fly GUI terbuka", Time = 3 })
	end
})

LeftGroupbox7:AddSlider("WalkSpeedSlider", {
	Text = "Walk Speed Value",
	Default = 1000,
	Max = 1000,
	Min = 16,
	Rounding = 1,
	Callback = function(state, arg191)
	end
})

LeftGroupbox7:AddCheckbox("NoClipToggle", {
	Text = "No Clip",
	Default = false,
	Callback = function(state, arg193)
		if state then
			local connection4 = RunService.RenderStepped:Connect(function(deltaTime11)
			end)
		else
			connection4:Disconnect()
			local descendants3 = Players.LocalPlayer.Character:GetDescendants()

			for k5, v7 in pairs(descendants3) do
				v7.CanCollide = true
			end
		end
	end
})

LeftGroupbox7:AddCheckbox("JumpPowerToggle", {
	Text = "Custom Jump Power",
	Default = false,
	Callback = function(state, arg195)
		if state then
			local Humanoid3 = Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
			Humanoid3.JumpPower = 50
		else
			local Humanoid4 = Players.LocalPlayer.Character:FindFirstChildOfClass("Humanoid")
			Humanoid4.JumpPower = 50
		end
	end
})

LeftGroupbox7:AddSlider("JumpPowerSlider", {
	Text = "Jump Power Value",
	Default = 50,
	Max = 300,
	Min = 0,
	Rounding = 0,
	Callback = function(state, arg197)
	end
})

RightGroupbox3:AddToggle("FakeTagEnabled", {
	Text = "Enable Fake Tag",
	Default = false,
	Callback = function(state, arg199)
	end
})

RightGroupbox3:AddInput("FakeTagText", {
	Text = "Chat Tag",
	Default = "[Kanzyu_script]",
	Finished = true,
	Numeric = false,
	Placeholder = "[Kanzyu_script]",
	Callback = function(state, arg201)
	end
})

LeftGroupbox9:AddButton({
	Text = "Apply Korless",
	Callback = function(state, arg203)
		task.wait()
		game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
		game.Players.LocalPlayer.Character:FindFirstChild("Right Leg")
		task.wait(0.1)
		game.Players.LocalPlayer.Character.Head.Transparency = 1

		if state then
			local face = game.Players.LocalPlayer.Character.Head:FindFirstChild("face")
			face:Destroy()
			game.Players.LocalPlayer.Character["Right Leg"].Transparency = 1
			local MeshPart = Instance.new("MeshPart")
			MeshPart.Name = "KorlessHead"
			MeshPart.Size = Vector3.new(1.5, 1.5, 1.5)
			MeshPart.CanCollide = false
			MeshPart.MeshId = "rbxassetid://902942096"
			MeshPart.TextureID = "rbxassetid://902843398"
			MeshPart.CFrame = (game.Players.LocalPlayer.Character["Right Leg"].CFrame * CFrame.new(0, 0.5, 0))
			MeshPart.Parent = game.Players.LocalPlayer.Character
			local WeldConstraint = Instance.new("WeldConstraint")
			WeldConstraint.Part0 = game.Players.LocalPlayer.Character["Right Leg"]
			WeldConstraint.Part1 = MeshPart
			WeldConstraint.Parent = MeshPart

			local connection5 = game.Players.LocalPlayer.CharacterAdded:Connect(function(character7)
				task.wait(1)
				task.wait()
				game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
				game.Players.LocalPlayer.Character:FindFirstChild("Right Leg")
				task.wait(0.1)
				game.Players.LocalPlayer.Character.Head.Transparency = 1
				local face3 = game.Players.LocalPlayer.Character.Head:FindFirstChild("face")
				face3:Destroy()
				game.Players.LocalPlayer.Character["Right Leg"].Transparency = 1
				local MeshPart3 = Instance.new("MeshPart")
				MeshPart3.Name = "KorlessHead"
				MeshPart3.Size = Vector3.new(1.5, 1.5, 1.5)
				MeshPart3.CanCollide = false
				MeshPart3.MeshId = "rbxassetid://902942096"
				MeshPart3.TextureID = "rbxassetid://902843398"
				MeshPart3.CFrame = (game.Players.LocalPlayer.Character["Right Leg"].CFrame * CFrame.new(0, 0.5, 0))
				MeshPart3.Parent = game.Players.LocalPlayer.Character
				local WeldConstraint3 = Instance.new("WeldConstraint")
				WeldConstraint3.Part0 = game.Players.LocalPlayer.Character["Right Leg"]
				WeldConstraint3.Part1 = MeshPart3
				WeldConstraint3.Parent = MeshPart3
			end)
		else
			local face2 = game.Players.LocalPlayer.Character.Head:FindFirstChild("face")
			face2:Destroy()
			game.Players.LocalPlayer.Character["Right Leg"].Transparency = 1
			local MeshPart2 = Instance.new("MeshPart")
			MeshPart2.Name = "KorlessHead"
			MeshPart2.Size = Vector3.new(1.5, 1.5, 1.5)
			MeshPart2.CanCollide = false
			MeshPart2.MeshId = "rbxassetid://902942096"
			MeshPart2.TextureID = "rbxassetid://902843398"
			MeshPart2.CFrame = (game.Players.LocalPlayer.Character["Right Leg"].CFrame * CFrame.new(0, 0.5, 0))
			MeshPart2.Parent = game.Players.LocalPlayer.Character
			local WeldConstraint2 = Instance.new("WeldConstraint")
			WeldConstraint2.Part0 = game.Players.LocalPlayer.Character["Right Leg"]
			WeldConstraint2.Part1 = MeshPart2
			WeldConstraint2.Parent = MeshPart2
			connection5:Disconnect()

			game.Players.LocalPlayer.CharacterAdded:Connect(function(character8)
				task.wait(1)
				task.wait()
				game.Players.LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
				game.Players.LocalPlayer.Character:FindFirstChild("Right Leg")
				task.wait(0.1)
				game.Players.LocalPlayer.Character.Head.Transparency = 1
				local face4 = game.Players.LocalPlayer.Character.Head:FindFirstChild("face")
				face4:Destroy()
				game.Players.LocalPlayer.Character["Right Leg"].Transparency = 1
				local MeshPart4 = Instance.new("MeshPart")
				MeshPart4.Name = "KorlessHead"
				MeshPart4.Size = Vector3.new(1.5, 1.5, 1.5)
				MeshPart4.CanCollide = false
				MeshPart4.MeshId = "rbxassetid://902942096"
				MeshPart4.TextureID = "rbxassetid://902843398"
				MeshPart4.CFrame = (game.Players.LocalPlayer.Character["Right Leg"].CFrame * CFrame.new(0, 0.5, 0))
				MeshPart4.Parent = game.Players.LocalPlayer.Character
				local WeldConstraint4 = Instance.new("WeldConstraint")
				WeldConstraint4.Part0 = game.Players.LocalPlayer.Character["Right Leg"]
				WeldConstraint4.Part1 = MeshPart4
				WeldConstraint4.Parent = MeshPart4
			end)
		end

		result:Notify({ Title = "Kanzyu_script", Description = "Korless Morph Applied", Time = 3 })
	end
})

LeftGroupbox8:AddToggle("HideName", {
	Text = "Streamer Mode",
	Default = false,
	Callback = function(state, arg205)
		if state then
			local PlayerGui2 = Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
			local descendants4 = PlayerGui2:GetDescendants()

			for i3, v8 in ipairs(descendants4) do
				tostring(v8.Text):find(Players.LocalPlayer.Name, 1, true)
				v8.Visible = false
			end

			local connection6 = PlayerGui2.DescendantAdded:Connect(function(descendant3)
				task.defer(function(...)
				end, descendant3)
			end)
		else
			connection6:Disconnect()
			local PlayerGui3 = Players.LocalPlayer:FindFirstChildOfClass("PlayerGui")
			local descendants5 = PlayerGui3:GetDescendants()

			for i4, v9 in ipairs(descendants5) do
				tostring(v9.Text):find(Players.LocalPlayer.Name, 1, true)
				v9.Visible = true
			end
		end
	end
})

LeftGroupbox8:AddCheckbox("Fullbright", {
	Text = "Fullbright",
	Default = false,
	Callback = function(state, arg207)
		if state then
			Lighting.Brightness = 2
			Lighting.ClockTime = 14
			Lighting.Ambient = Color3.new(1, 1, 1)
			Lighting.OutdoorAmbient = Color3.new(1, 1, 1)
			Lighting.GlobalShadows = true
		else
			Lighting.Brightness = 1
			Lighting.ClockTime = 0
			Lighting.Ambient = Lighting.Ambient
			Lighting.OutdoorAmbient = Lighting.OutdoorAmbient
		end
	end
})

LeftGroupbox8:AddCheckbox("NoShadow", {
	Text = "No Shadow",
	Default = false,
	Callback = function(state, arg209)
	end
})

LeftGroupbox8:AddCheckbox("LowGraphics", {
	Text = "Low Graphics",
	Default = false,
	Callback = function(state, arg211)
		if state then
			local result5 = settings()
			result5.Rendering.QualityLevel = Enum.QualityLevel.Level01
		else
			local result6 = settings()
			result6.Rendering.QualityLevel = Enum.QualityLevel.Automatic
		end
	end
})

LeftGroupbox8:AddCheckbox("NoScreenEffects", {
	Text = "No Screen Effects",
	Default = false,
	Callback = function(state, arg213)
		if state then
			local children2 = Lighting:GetChildren()

			for k6, v10 in pairs(children2) do
				v10.Enabled = false
				v10.Enabled = false
				v10.Enabled = false
				v10.Enabled = false
				v10.Enabled = false
			end
		else
			v10.Enabled = false
		end
	end
})

LeftGroupbox8:AddCheckbox("CleanSky", {
	Text = "Clean Sky",
	Default = false,
	Callback = function(state, arg215)
		if state then
			local children3 = Lighting:GetChildren()

			for i5, v11 in ipairs(children3) do
				v11:Destroy()
			end
		end
	end
})

RightGroupbox5:AddCheckbox("ThirdPersonToggle", {
	Text = "Third Person View",
	Default = false,
	Callback = function(state, arg217)
	end
})

RightGroupbox5:AddToggle("UnlimitedZoom", {
	Text = "Unlimited Zoom Out",
	Default = false,
	Callback = function(state, arg219)
		if state then
			Players.LocalPlayer.CameraMaxZoomDistance = 1000
			Players.LocalPlayer.CameraMinZoomDistance = 0
		else
			Players.LocalPlayer.CameraMaxZoomDistance = 128
			Players.LocalPlayer.CameraMinZoomDistance = 0.5
		end
	end
})

RightGroupbox5:AddSlider("MaxZoomDistance", {
	Text = "Max Zoom Distance",
	Default = 1000,
	Max = 5000,
	Min = 100,
	Rounding = 0,
	Callback = function(state, arg221)
	end
})

RightGroupbox5:AddToggle("CustomFOV", {
	Text = "Custom FOV",
	Default = false,
	Callback = function(state, arg223)
		workspace.CurrentCamera.FieldOfView = 70
	end
})

RightGroupbox5:AddSlider("CameraFOV", {
	Text = "Camera FOV",
	Default = 70,
	Max = 120,
	Min = 40,
	Rounding = 0,
	Callback = function(state, arg225)
	end
})

RightGroupbox4:AddSlider("ClockTime", {
	Text = "Clock Time",
	Default = 14,
	Max = 24,
	Min = 0,
	Rounding = 0,
	Callback = function(state, arg227)
		Lighting.Ambient = Color3.fromRGB(255, 255, 255)
		Lighting.OutdoorAmbient = Color3.fromRGB(255, 255, 255)
		Lighting.Brightness = 2

		if state then
			Lighting.ClockTime = state
		else
			Lighting.ClockTime = false
		end
	end
})

RightGroupbox4:AddSlider("Brightness", {
	Text = "Brightness",
	Default = 2,
	Max = 5,
	Min = 0,
	Rounding = 1,
	Callback = function(state, arg229)
		Lighting.Ambient = Color3.fromRGB(255, 255, 255)
		Lighting.OutdoorAmbient = Color3.fromRGB(255, 255, 255)

		if state then
			Lighting.Brightness = state
		else
			Lighting.Brightness = false
		end

		Lighting.ClockTime = false
	end
})

LeftGroupbox10:AddToggle("ShowCustomCursor", {
	Text = "Custom Cursor",
	Default = true,
	Callback = function(state, arg231)
		if state then
			result.ShowCustomCursor = state
		else
			result.ShowCustomCursor = false
		end
	end
})

LeftGroupbox10:AddDropdown("NotificationSide", {
	Text = "Notification Side",
	Default = "Right",
	Values = { "Left", "Right" },
	Callback = function(state, arg233)
		if state then
			result:SetNotifySide(state)
		else
			result:SetNotifySide(false)
		end
	end
})

LeftGroupbox10:AddDropdown("DPIDropdown", {
	Text = "DPI Scale",
	Default = "85%%",
	Values = { "50%", "75%", "85%", "100%", "125%", "150%" },
	Callback = function(arg234, arg235)
		local result7 = arg234:gsub("%%", "")
		result:SetDPIScale(tonumber(result7))
	end
})

LeftGroupbox10:AddToggle("HeaderGlowToggle", {
	Text = "Glow AccentBar",
	Default = true,
	Callback = function(state, arg237)
		if state then
			Window:SetHeaderGlow(state)
		else
			Window:SetHeaderGlow(false)
		end
	end
})

LeftGroupbox10:AddToggle("ShowProfile", {
	Text = "Show Profile",
	Default = true,
	Callback = function(state, arg239)
		if state then
			Window:SetProfileVisible(state)
		else
			Window:SetProfileVisible(false)
		end
	end
})

LeftGroupbox10:AddDivider()
local Label = LeftGroupbox10:AddLabel("Menu bind")
Label:AddKeyPicker("MenuKeybind", { Text = "Menu keybind", Default = "RightShift", NoUI = true })

LeftGroupbox10:AddButton("Unload script", function(arg240, arg241)
	result:Unload()
end)

result2:SetLibrary(result)
result3:SetLibrary(result)
result3:IgnoreThemeSettings()
result3:SetIgnoreIndexes({})
result2:SetFolder("Kanzyu_script")
result3:SetFolder("Kanzyu_script/configs")
result3:BuildConfigSection(Tab6)
result2:ApplyToTab(Tab6)
result3:LoadAutoloadConfig()
